namespace: cloin
name: eda
version: 1.0.1
readme: README.md
authors:
  - Colin McNaughton <c.a.mcnaughton@gmail.com>
description: Event-Driven Ansible content
license_file: 'LICENSE'
tags:
  - eda
  - elasticsearch
  - infrastructure
dependencies: {}
repository: https://github.com/cloin/cloin.eda
documentation: https://github.com/cloin/cloin.eda
issues: https://github.com/cloin/cloin.eda
build_ignore: []
