- name: Elastic events
  hosts: localhost
  sources:
    - cloin.eda.elastic_http:
        elastic_host: "{{ elk_host | default('localhost') }}" # IP or fqdn - do not use https or http prefix
        elastic_port: "{{ elk_port | default('9200' }}" # port number, default is 9200
        elastic_username: "{{ elk_username | default('elastic') }}" # elastic username, default is elastic
        elastic_password: "{{ elk_password | default('elastic') }}" # elastic password
        elastic_index_pattern: "{{ elk_index_pattern | default('filebeat-*') }}" # index pattern default is filebeat-*
        query: |
          term:
            container.name.keyword: nginx
        interval: 5

  rules:
    - name: Debug event
      condition: 
        all:
          - event.ecs is defined 
          - event.nginx.log_level == "error"
      action:
        debug:
