- name: New Ansible blog post notifier
  hosts: localhost
  sources:
    - name: RSS feed items as events
      rss:
        feed_configs:
          - name: Ansible blog
            url: https://www.ansible.com/blog/rss.xml
            search: ""
            content_tags: tags
            interval: 300

          - name: HackerNews
            url: https://hnrss.org/frontpage
            search:
            content_tags:
            interval:

          - name: Cloin Mastodon
            url: https://techhub.social/@cloin.rss
            search:
            content_tags:
            interval: 3600

        interval: 7200
        most_recent_item: true
      filters:
        - ansible.eda.json_filter:
            exclude_keys:
              - content
              - summary_detail

  rules:
    - name: New EDA blog
      condition: |
        event.feed_name == "Ansible blog" and
        event.content_tags is search("Event-Driven Ansible",ignorecase=true)
      action:
        debug:

    - name: New HackerNews frontpage post
      condition: |
        event.feed_name == "HackerNews"
      action:
        debug:

    - name: New Mastodon post by Cloin
      condition: |
        event.feed_name == "Cloin Mastodon"
      action:
        debug:
