name: Release Ansible Collection

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible pyyaml

    - name: Update galaxy.yml with new version
      run: |
        export NEW_VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
        sed -i "s/version: .*/version: $NEW_VERSION/" galaxy.yml

    - name: Build Ansible Collection
      run: ansible-galaxy collection build

    - name: Extract namespace and collection name from galaxy.yml
      run: |
        python -c "import yaml; data = yaml.safe_load(open('galaxy.yml')); print(f'::set-output name=namespace::{data['namespace']}') " | tee -a $GITHUB_ENV
        python -c "import yaml; data = yaml.safe_load(open('galaxy.yml')); print(f'::set-output name=collection::{data['name']}') " | tee -a $GITHUB_ENV

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}

    - name: Upload Collection to GitHub Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./$NAMESPACE-$COLLECTION-$NEW_VERSION.tar.gz
        asset_name: $NAMESPACE-$COLLECTION-$NEW_VERSION.tar.gz
        asset_content_type: application/gzip

    - name: Publish to Ansible Galaxy
      run: ansible-galaxy collection publish ./$NAMESPACE-$COLLECTION-$NEW_VERSION.tar.gz --api-key=${{ secrets.ANSIBLE_GALAXY_API_KEY }}
